export enum TokenType {
    ACCESS = 'ACCESS',
    REFRESH = 'REFRESH',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    PHONE_VERIFICATION = 'PHONE_VERIFICATION',
    PASSWORD_RESET = 'PASSWORD_RESET',
    INVITATION = 'INVITATION',
}
