// packages/common/enums/user-role.enum.ts
export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  VENUE_ADMIN = 'VENUE_ADMIN',
  USER = 'USER',
  BMSP_SUPER_ADMIN = 'BMSP_SUPER_ADMIN',
  BMSP_ADMIN = 'BMSP_ADMIN',
  BMSP_FINANCE_ADMIN = 'BMSP_FINANCE_ADMIN',
  BMSP_VENUES_ADMIN = 'BMSP_VENUES_ADMIN',
  BMSP_REGIONAL_VENUES_ADMIN = 'BMSP_REGIONAL_VENUES_ADMIN',
  BMSP_BOOKINGS_ADMIN = 'BMSP_BOOKINGS_ADMIN',
  BMSP_CUSTOMER_CARE = 'BMSP_CUSTOMER_CARE',
  VENUE_OWNER = 'VENUE_OWNER',
  SECONDARY_VENUE_NAME_MANAGER = 'SECONDARY_VENUE_NAME_MANAGER',
  VENUE_BOOKING_MANAGER = 'VENUE_BOOKING_MANAGER',
  VENUE_OPERATIONS_MANAGER = 'VENUE_OPERATIONS_MANAGER',
  ANONYMOUS = 'ANONYMOUS',
  SYSTEM = 'SYSTEM',
}